included:
  - Sources
  - Tests
disabled_rules:
  - line_length          # swift-format handles this
  - trailing_whitespace  # swift-format handles this
opt_in_rules:
  - force_unwrapping
  - implicitly_unwrapped_optional
excluded:
  - .build
