// ABOUTME: Emit the playwright.config.ts that materialises one Playwright project per declared browser.
// ABOUTME: JSON reporter feeds the Rust ingest; HTML + trace/video/screenshot feed the human debugging a failure.

use std::fmt::Write as _;

use crate::error::Result;
use crate::parser::step::Browser;

/// File the JSON reporter writes, relative to the workspace root. The Rust
/// side reads its verdicts and the `mirroir-captures` attachment back out.
pub const JSON_REPORT_FILE: &str = "playwright-report.json";

/// Directory the HTML reporter writes, relative to the workspace root. It is
/// what a human opens after a failure.
pub const HTML_REPORT_DIR: &str = "report-html";

/// Directory the per-test artifacts — `trace.zip`, `video.webm`,
/// `test-failed-1.png` — are written to, relative to the workspace root.
///
/// Declaring it is load-bearing: left to its default, Playwright roots the
/// output at whichever ancestor directory carries a `package.json`, which
/// scatters a run's artifacts outside the workspace that produced them.
pub const ARTIFACT_DIR: &str = "test-results";

/// Emit a Playwright config that materialises one `projects:` entry per
/// requested browser.
///
/// Both reporters are on: JSON for the Rust ingest, HTML for the human who
/// reads a failure. `use:` keeps a trace, a screenshot, and a video of every
/// failing test — the artifacts the debugging loop opens — and they survive
/// the run because the workspace is a real directory, not a tempdir.
///
/// `retries: 0` and `fullyParallel: false` are deliberate and load-bearing:
/// mirroir-run owns retry policy (a retried browser step would hide a flaky
/// assertion from the drift detector), and the sample's session-scoped boot
/// owns the server, so two tests must not drive it at once.
///
/// # Errors
///
/// [`crate::error::RunnerError::Format`] on `std::fmt::Write` failure
/// (unreachable for `String`).
pub fn emit_playwright_config(browsers: &[Browser]) -> Result<String> {
    let mut s = String::new();
    writeln!(s, "// AUTO-GENERATED by mirroir-run — DO NOT EDIT.")?;
    writeln!(
        s,
        "import {{ defineConfig, devices }} from '@playwright/test';"
    )?;
    writeln!(s)?;
    writeln!(s, "export default defineConfig({{")?;
    writeln!(s, "  testDir: '.',")?;
    writeln!(s, "  outputDir: '{ARTIFACT_DIR}',")?;
    writeln!(
        s,
        "  fullyParallel: false,            // session-scoped boot owns the server"
    )?;
    writeln!(
        s,
        "  retries: 0,                      // mirroir-run owns retry policy"
    )?;
    writeln!(
        s,
        "  reporter: [['json', {{ outputFile: '{JSON_REPORT_FILE}' }}], ['html', {{ outputFolder: '{HTML_REPORT_DIR}', open: 'never' }}]],"
    )?;
    writeln!(s, "  use: {{")?;
    writeln!(
        s,
        "    // `on-first-retry` never fires under `retries: 0`; a failure's"
    )?;
    writeln!(
        s,
        "    // trace is exactly what the debugging loop needs, so keep it."
    )?;
    writeln!(s, "    trace: 'retain-on-failure',")?;
    writeln!(s, "    screenshot: 'only-on-failure',")?;
    writeln!(s, "    video: 'retain-on-failure',")?;
    writeln!(s, "  }},")?;
    writeln!(s, "  projects: [")?;
    for browser in browsers {
        let (name, device) = match browser {
            Browser::Chrome => ("chromium", "Desktop Chrome"),
            Browser::Firefox => ("firefox", "Desktop Firefox"),
            Browser::Webkit => ("webkit", "Desktop Safari"),
        };
        writeln!(
            s,
            "    {{ name: '{name}', use: {{ ...devices['{device}'] }} }},"
        )?;
    }
    writeln!(s, "  ],")?;
    writeln!(s, "}});")?;
    Ok(s)
}

#[cfg(test)]
mod tests {
    use std::error::Error as StdError;
    use std::result::Result as StdResult;

    use super::*;

    type TestResult = StdResult<(), Box<dyn StdError>>;

    fn assert_contains(haystack: &str, needle: &str) -> TestResult {
        if haystack.contains(needle) {
            Ok(())
        } else {
            Err(format!("expected `{needle}` in output, got:\n{haystack}").into())
        }
    }

    #[test]
    fn emits_playwright_config_with_all_three_browsers() -> TestResult {
        let cfg = emit_playwright_config(&[Browser::Chrome, Browser::Firefox, Browser::Webkit])?;
        assert_contains(&cfg, "import { defineConfig, devices }")?;
        assert_contains(&cfg, "name: 'chromium'")?;
        assert_contains(&cfg, "name: 'firefox'")?;
        assert_contains(&cfg, "name: 'webkit'")?;
        assert_contains(&cfg, "devices['Desktop Chrome']")?;
        assert_contains(&cfg, "devices['Desktop Firefox']")?;
        assert_contains(&cfg, "devices['Desktop Safari']")?;
        assert_contains(&cfg, "playwright-report.json")?;
        Ok(())
    }

    /// The `use:` block is what makes a failure debuggable, and the two
    /// zeroed knobs are deliberate — mirroir-run owns retry policy, and the
    /// sample's session-scoped boot owns the server.
    #[test]
    fn config_keeps_the_failure_artifacts_and_the_deliberate_zeros() -> TestResult {
        let cfg = emit_playwright_config(&[Browser::Chrome])?;
        for needle in [
            "testDir: '.',",
            "outputDir: 'test-results',",
            "fullyParallel: false,            // session-scoped boot owns the server",
            "retries: 0,                      // mirroir-run owns retry policy",
            "['html', { outputFolder: 'report-html', open: 'never' }]",
            "trace: 'retain-on-failure',",
            "screenshot: 'only-on-failure',",
            "video: 'retain-on-failure',",
        ] {
            assert_contains(&cfg, needle)?;
        }
        Ok(())
    }
}
