// ABOUTME: Emits the header and shared helpers every compiled spec opens with.
// ABOUTME: Provenance banner, `_by` (labels), `_center` (pointer parking), `_watch` (invariants).

use std::fmt::Write as _;
use std::fs;
use std::path::Path;

use sha2::{Digest, Sha256};

use crate::error::{Result, RunnerError};

/// Where a compiled spec came from.
///
/// Emitted verbatim into the spec's header so a reader of
/// `target/playwright/…/x.spec.ts` can name the YAML that produced it and
/// tell whether the file still matches that YAML.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ScenarioSource {
    /// The scenario YAML's path, as the invocation named it.
    pub path: String,
    /// `sha256:<hex>` over that file's bytes.
    pub digest: String,
}

impl ScenarioSource {
    /// Read `path` and record its digest.
    ///
    /// # Errors
    ///
    /// [`RunnerError::Io`] when the file can't be read.
    pub fn read(path: &Path) -> Result<Self> {
        let bytes = fs::read(path).map_err(|source| RunnerError::Io {
            context: format!("hash scenario file {}", path.display()),
            source,
        })?;
        let digest = Sha256::digest(&bytes);
        Ok(Self {
            path: path.display().to_string(),
            digest: format!("sha256:{}", hex::encode(digest)),
        })
    }
}

/// Resource types whose failed responses fail the test. A page depends on
/// these to do its job; the browser's own speculative fetches (favicon,
/// prefetch, beacons) arrive as other types and say nothing about the
/// scenario.
const WATCHED_RESOURCE_TYPES: [&str; 5] = ["document", "script", "stylesheet", "fetch", "xhr"];

/// Emit the imports and the helpers every step and every test share: `_by`
/// (label resolution), `_center` (pointer parking for wheel events), and
/// `_watch` (the browser-side invariants every scenario gets for free).
///
/// # Errors
///
/// [`crate::error::RunnerError::Format`] on `std::fmt::Write` failure
/// (unreachable for `String`).
pub fn emit_prelude(source: &ScenarioSource, body: &mut String) -> Result<()> {
    writeln!(body, "// AUTO-GENERATED by mirroir-run — DO NOT EDIT.")?;
    writeln!(body, "// Source: {}", source.path)?;
    writeln!(body, "// Source hash: {}", source.digest)?;
    writeln!(body, "import {{ test, expect }} from '@playwright/test';")?;
    writeln!(body)?;
    emit_by_helper(body)?;
    emit_center_helper(body)?;
    emit_watch_helper(body)?;
    Ok(())
}

/// The label-resolution helper. Raw CSS and Playwright locator-engine strings
/// pass straight through; a bare label resolves through Playwright's own
/// locator priority — role-based and user-facing locators first, the test
/// attribute next, visible text last.
fn emit_by_helper(body: &mut String) -> Result<()> {
    writeln!(
        body,
        "// Helper: pass through raw CSS and Playwright locator-engine strings"
    )?;
    writeln!(
        body,
        "// (role=, text=, xpath=, css=, id=, data-testid=); otherwise resolve a"
    )?;
    writeln!(
        body,
        "// bare label in Playwright's own locator priority — role, then label,"
    )?;
    writeln!(
        body,
        "// then placeholder, then the data-test attribute, then visible text."
    )?;
    writeln!(body, "const _by = (page, label) => {{")?;
    writeln!(
        body,
        "  if (/^[\\[#.:>*]/.test(label)) return page.locator(label);"
    )?;
    writeln!(
        body,
        "  if (/^(role|text|xpath|css|id|data-testid)=/.test(label)) return page.locator(label);"
    )?;
    writeln!(
        body,
        "  return page.getByRole('button', {{ name: label, exact: true }})"
    )?;
    writeln!(
        body,
        "    .or(page.getByRole('link', {{ name: label, exact: true }}))"
    )?;
    writeln!(body, "    .or(page.getByLabel(label, {{ exact: true }}))")?;
    writeln!(
        body,
        "    .or(page.getByPlaceholder(label, {{ exact: true }}))"
    )?;
    writeln!(body, "    .or(page.locator(`[data-test=\"${{label}}\"]`))")?;
    writeln!(body, "    .or(page.getByText(label, {{ exact: true }}));")?;
    writeln!(body, "}};")?;
    writeln!(body)?;
    Ok(())
}

/// The pointer-parking helper a `swipe:` step calls before its wheel event.
fn emit_center_helper(body: &mut String) -> Result<()> {
    writeln!(
        body,
        "// Helper: park the pointer over the page so a wheel event lands on the"
    )?;
    writeln!(
        body,
        "// content instead of the (0, 0) corner it starts at."
    )?;
    writeln!(body, "const _center = async (page) => {{")?;
    writeln!(
        body,
        "  const vp = page.viewportSize() ?? {{ width: 1280, height: 720 }};"
    )?;
    writeln!(
        body,
        "  await page.mouse.move(vp.width / 2, vp.height / 2);"
    )?;
    writeln!(body, "}};")?;
    writeln!(body)?;
    Ok(())
}

/// The browser-side invariant collector. Every scenario gets it: a page that
/// threw an uncaught exception, or whose own resources failed to load, is a
/// failure even when every locator resolved and every assertion held.
fn emit_watch_helper(body: &mut String) -> Result<()> {
    let watched = WATCHED_RESOURCE_TYPES
        .iter()
        .map(|kind| format!("'{kind}'"))
        .collect::<Vec<_>>()
        .join(", ");
    writeln!(
        body,
        "// Helper: the invariants every scenario gets for free — an uncaught"
    )?;
    writeln!(
        body,
        "// exception, or a failed response for a resource the page depends on."
    )?;
    writeln!(body, "const _WATCHED_RESOURCES = [{watched}];")?;
    writeln!(body, "const _watch = (page, sink) => {{")?;
    writeln!(
        body,
        "  page.on('pageerror', (error) => {{ sink.page_errors.push(String(error)); }});"
    )?;
    writeln!(body, "  page.on('response', (response) => {{")?;
    writeln!(body, "    const request = response.request();")?;
    writeln!(
        body,
        "    if (response.status() >= 400 && _WATCHED_RESOURCES.includes(request.resourceType())) {{"
    )?;
    writeln!(
        body,
        "      sink.failed_requests.push(`${{response.status()}} ${{request.method()}} ${{response.url()}}`);"
    )?;
    writeln!(body, "    }}")?;
    writeln!(body, "  }});")?;
    writeln!(body, "}};")?;
    writeln!(body)?;
    Ok(())
}
